Gepa/Gepa.Site/Controllers/ClassPlansController.cs
using AutoMapper;
using Gepa.Entities.Framework.Entities.ClassPlans;
using Gepa.Site.Helpers;
using Gepa.Site.Models.ClassPlans;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Gepa.Site.Controllers
{
    [Authorize]
    public class ClassPlansController : GepaBaseController
    {
        // GET: ClassPlans
        public ActionResult Index()
        {
            return View("ClassPlanDetails", new ClassPlanModel { Id = -1 });//Indica que é um novo plano de aula
        }

        [HttpPost]
        public async Task<ActionResult> SaveClassPlan(ClassPlanModel classPlanModel)
        {
            if (classPlanModel.Id < 0)//Novo plano de aula
            {
                var newClassPlan = Mapper.Map<ClassPlanModel, ClassPlan>(classPlanModel);
                var currentTeacher = await Helper.GetCurrentTeacherAsync();
                newClassPlan.TeacherId = currentTeacher.TeacherId;
                await ClassPlanService.InsertClassPlanAsync(newClassPlan);
                return Json(Url.Action("Index", "Dashboard"));
            }
            else if(classPlanModel.Id > 0)
            {
                var classPlan = Mapper.Map<ClassPlanModel, ClassPlan>(classPlanModel);
                ClassPlanService.UpdateClassPlan(classPlan);
                return Json(Url.Action("Index", "Dashboard"));
            }

            return View("ClassPlanDetails", classPlanModel);
        }

        public ActionResult ClassGoalsModalView(ClassGoalsModel classGoalsModel)
        {
            return PartialView("_AddClassGoalsModal", classGoalsModel);
        }

        public ActionResult LessonContentModalView(LessonsContentModel lessonsContentModel)
        {
            return PartialView("_AddLessonContentModal", lessonsContentModel);
        }

        public ActionResult EvaluationModalView(EvaluationModel evaluationModel)
        {
            return PartialView("_AddEvaluationModal", evaluationModel);
        }
        
        public ActionResult ChoresModalView(ChoresModel choresModel)
        {
            return PartialView("_AddChoresModal", choresModel);
        }

        public async Task<ActionResult> EditClassPlan(long classPlanId)
        {
            var classPlan = await ClassPlanService.FindClassPlanAsync(classPlanId);
            var model = Mapper.Map<ClassPlan, ClassPlanModel>(classPlan);
            return View("ClassPlanDetails", model);
        }

        public ActionResult RemoveClassPlan(long classPlanId)
        {
            var classPlan = ClassPlanService.FindClassPlan(classPlanId);
            ClassPlanService .DeleteClassPlan(classPlan);

            var classPlans = ClassPlanService.FindAllClassPlans();
            var model = Mapper.Map<List<ClassPlanModel>>(classPlans);

            return RedirectToAction("Index", "Dashboard", model);
        }
    }
}

Gepa/Gepa.Site/Controllers/DashboardController.cs
using AutoMapper;
using Gepa.Entities.Framework.Entities.ClassPlans;
using Gepa.Site.Helpers;
using Gepa.Site.Models.ClassPlans;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Gepa.Site.Controllers
{
    [Authorize]
    public class DashboardController : GepaBaseController
    {
        // GET: Dashboard
        public async Task<ActionResult> Index()
        {
            var currentTeacher = await Helper.GetCurrentTeacherAsync();
            var classPlans = await ClassPlanService.FindAllTeacherClassPlans(currentTeacher.TeacherId, true);
            var model = Mapper.Map<List<ClassPlanModel>>(classPlans);
            var user = Helper.GetCurrentUser();
            if (string.IsNullOrWhiteSpace(currentTeacher.Name))
                ViewBag.UserName = user.UserName;
            else
                ViewBag.UserName = currentTeacher.Name;
            return View(model);
        }
    }
}

Gepa/Gepa.Site/Views/Dashboard/Index.cshtml
@model List<Gepa.Site.Models.ClassPlans.ClassPlanModel>

@{
    ViewBag.Title = "Painel Principal";
}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">
        <img src="~/Content/Images/Gepa_Logo.png" class="d-inline-block align-top" alt="">
        @Language.Gepa
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    @Language.ClassPlan
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="@Url.Action("Index","ClassPlans")">@Language.Register2</a>
                </div>
            </li>

            @*<li class="nav-item">
                <a class="nav-link" href="#">Módulos</a>
            </li>*@
        </ul>
        @Html.Partial("_UserMenuPartial", (string)ViewBag.UserName)
    </div>
</nav>

<div>

    <h1 class="gepaTitles" style="text-align: center;">@Language.ClassPlans</h1>

    @if (Model.Count > 0)
    {
        <input class="form-control gepa-table-search " id="classPlanSearch" type="text" placeholder="@(Language.Search + "...")">
        <table id="classPlansTable" class="table table-bordered table-striped tablesorter">
            <thead>
                <tr>
                    <th scope="col" style="width: 50px;"></th>
                    <th scope="col">@Language.Title</th>
                    <th scope="col">@Language.Subject</th>
                    <th scope="col">@Language.Date</th>
                    <th scope="col" style="width: 150px;"></th>
                </tr>
            </thead>
            <tbody>

                @foreach (var classPlan in Model)
                {
                    <tr class="classPlanRow link-row" data-href="@Url.Action("EditClassPlan", "ClassPlans", new { classPlanId = classPlan.Id })">
                        <td>
                            <div style="display: flex">
                                @if (classPlan.Chores.FindAll(c => c.IsCompletedTask == false).ToList().Count > 0)
                                {
                                    <span class="alertPendencies" data-toggle="tooltip" data-placement="top" title="@Language.ChorePendencyMessage">
                                        <i class="fas fa-exclamation-circle icon chorePendencies"></i>
                                    </span>
                                }

                                @if (classPlan.ClassGoals.FindAll(c => c.IsCompleted == false).ToList().Count > 0)
                                {
                                    <span class="alertPendencies" data-toggle="tooltip" data-placement="top" title="@Language.ClassGoalPendencyMessage">
                                        <i class="fas fa-exclamation-triangle icon classGoalsPendencies"></i>
                                    </span>
                                }
                            </div>
                        </td>

                        <td>@classPlan.Title</td>
                        <td>@classPlan.Subject</td>
                        <td>
                            @if (classPlan.Date != null)
                            {
                                @(((DateTime)classPlan.Date).ToString("dd/MM/yyyy"))
                            }

                        </td>

                        <td>
                            <a class="removeClassPlan" data-href="@Url.Action("RemoveClassPlan", "ClassPlans", new { classPlanId = classPlan.Id })" data-toggle="tooltip" data-placement="top" title="@Language.Exclude">
                                <i class="fas fa-trash icon"></i>
                                @Language.Exclude
                            </a>
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    }
    else
    {
        <div class="border noClassPlansMessage">
            <h3>@Language.NoClassPlanSaved</h3>
        </div>
    }
</div>

@Html.Partial("_RemoveClassPlanConfirmationDialog")

@section Scripts {
    @Scripts.Render("~/bundles/tablesorter")
}

<script type="text/javascript">

    var removeSelectedClassPlanUrl = null;

    $(document).ready(function (e) {
        $('.classPlanRow').click(function (e) {
            window.location = $(this).data("href");
        });

        $('.removeClassPlan').click(function (e) {
            e.stopPropagation();
            $("#confirmDeleteClassPlanModal").modal('toggle');
            removeSelectedClassPlanUrl = $(this).data("href");
            //window.location = $(this).data("href");
        });

        $("#classPlansTable").tablesorter(
            {
                dateFormat: 'pt',
                headers: {
                    0: {
                        sorter: false
                    }, 
                    4: {
                        sorter: false
                    }
                }
            });

        $("#classPlanSearch").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#classPlansTable tbody tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>

<style>
</style>

Gepa/Gepa.Site/Views/Dashboard/_RemoveClassPlanConfirmationDialog.cshtml
<div class="modal fade" id="confirmDeleteClassPlanModal" tabindex="-1" role="dialog" aria-labelledby="confirmDeleteClassPlanModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Excluir plano de aula</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <span>Você deseja excluir o plano de aula?</span>
            </div>

            <div class="modal-footer">
                <button type="button" id="btnRemoveClassPlan" class="btn btn-primary btnModals btnSaveModals">@Language.Exclude</button>
                <button type="button" id="btnCancelRemoveClassPlan" class="btn btn-secondary btnModals btnCancelModals" data-dismiss="modal">@Language.Cancel</button>

            </div>

        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $("#btnRemoveClassPlan").click(function () {
            window.location = removeSelectedClassPlanUrl;
        });

        $("#btnCancelRemoveClassPlan").click(function () {
            removeSelectedClassPlanUrl = null;
        });
    });
</script>